import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import HomeScreen from "../components/HomeScreen";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>RobuEdX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <Main>
        <Navbar />
        <HomeScreen/>
      </Main>
    </div>
  );
}

const Main = styled.main`
  display:flex;
  flex-direction:column;
  align-items:center;
  background-color: #1F1F1F;
  min-height:100vh;
`