import { getCookie } from "cookies-next";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import HomeScreen from "../components/HomeScreen";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import jwt from 'jsonwebtoken'
import User from '../models/User'


export default function Home({email,name,image}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>RobuEdX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Navbar email={email} name={name} image={image}/>
        <HomeScreen />
      </Main>
    </div>
  );
}

const Main = styled.main`
  display: flex;
  flex-direction: column;
  align-items: center;
  background-color: #1f1f1f;
  min-height: fit-content;
`;

export async function getServerSideProps({ req, res }) {
  try {
    const token = getCookie("user-token", { req, res });
    if (token){
      const verified = jwt.verify(token,process.env.JWT_SECRET);
      const obj = await User.findOne({ _id: verified.id });

      if(obj){
        return{
          props:{
            email:obj.email,
            name:obj.name,
            image:obj.imageUrl
          }
        }
      }
    };
    return { props: {} };
  } catch (error) {
    return { props: {} };
  }
}


