import dynamic from "next/dynamic";
import Login from "../components/LoginScreen";
import Footer from "../components/Footer";
import Head from "next/head";
const Navbar = dynamic(() => import("../components/Navbar"));
const LoginPage = () => {
  return (
    <>
      <Head>
        <title>Open Robotics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar whiteBar={true} />
      <Login />
      <Footer />
    </>
  );
};

export default LoginPage;
