import axios from "axios";
import Head from "next/head";
import React, { useEffect } from "react";
import ThankYouScreen from "../components/ThankYouScreen";
const stripe = require("stripe")(process.env.STRIPE_SECRET_KEY);

const ThankYou = ({ customer }) => {
  return (
    <div>
      <Head>
        <title>Thank you</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {customer && <ThankYouScreen customerName={customer.name} />}
    </div>
  );
};

export default ThankYou;

export async function getServerSideProps(req, res) {
  if (!req.query.session_id) {
    return {
      redirect: { destination: "/pricing" },
    };
  }
  try {
    const subscriptionDetail = await axios.post(
      "http://localhost:3000/api/subscription",
      {
        session_id: req.query?.session_id,
      }
    );
    const session = await stripe.checkout.sessions.retrieve(
      req.query?.session_id
    );
    const customer = await stripe.customers.retrieve(session.customer);
    if (subscriptionDetail.status===201) {

      return {
        props: {
          customer,
        },
      };
    }
  } catch (error) {
    console.log(error);
    return { redirect: { destination: "/" } };
  }
}
